import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import ClientOnly from '../components/ClientOnly'
import ConnectWallet from '../components/ConnectWallet'
import Tickers from '../components/Tickers'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ClientOnly>
          <ConnectWallet />
          <Tickers />
        </ClientOnly>
      </main>
    </div>
  )
}

export default Home
